version: '1.0'
services:
  webapi:
    build:
      dockerfile: Dockerfile
    ports: -"7979:80"
    environment:
      - CcustomerApi_ConnectionStrings_DefaultConnection=Server=db;MyDatabase=CrudTestAtDb;User=Sa;Password=Password123456%
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    ports: -"42609:1433"
    environment:
      SA_PASSWROD: Password123456%
      ACCEPT_EULA: "Y"
